research_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: news_researcher

summarise_task:
  description: >
    Summarise the information you received into a more concise format.
  expected_output: >
    A short summary of the information you received, containing all of the information but written in a very concise format.
    Regular text
  agent: summary_writer

write_poem_task:
  description: >
    Write a poem about {topic}, including all of the found information.
  expected_output: >
    A short poem
  agent: poet

paint_task:
  description: >
    Paint a picture representing the prompt
  expected_output: >
    An image representing the poem
  agent: painter