research_news_task:
  description: >
    Research and gather comprehensive information about the provided input.
    Focus on finding relevant, factual, and up-to-date information.
  expected_output: >
    A structured list of key findings and relevant information about the topic
  agent: news_researcher

summarise_task:
  description: >
    Create a concise summary of the provided input information.
  expected_output: >
    A clear and concise summary of the input information
  agent: summary_writer

write_poem_task:
  description: >
    Create a poem based on the provided input information.
    Use a direct and impactful writing style.
  expected_output: >
    A poem incorporating the provided information
  agent: poet

narrate_task:
  description: >
    Generate an audio narration of the provided input text.
  expected_output: >
    An audio narration of the input text
  agent: tts_narrator