research_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 5 bullet points of the most relevant information about {topic}
  agent: news_researcher

summarise_task:
  description: >
    Summarise the information you received into a more concise format.
  expected_output: >
    A short summary of the information you received, containing all of the information but written in a very concise format.
    Regular text
  agent: summary_writer

write_poem_task:
  description: >
    Write a poem about {topic}, including all of the found information. Hemingway style, short and direct.
  expected_output: >
    A short poem
  agent: poet

paint_task:
  description: >
    Paint a picture representing the topic
  expected_output: >
    An image representing the poem
  agent: painter

narrate_task:
  description: >
    Convert the provided text to speech using the most appropriate voice.
    Choose from available voices: alloy, echo, fable, onyx, nova, or shimmer.
  expected_output: >
    An audio file containing the narrated text
  agent: tts_narrator